### ISSUE TITLE
[Bug]: Crash Upon World Creation Attempt

### ISSUE THREAD

**Issue by CraftyZombie** [Mrbysco/MimicWorld#1]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.19

### Minecraft version

1.20.1

### Mod version

1.0.0

### Java version

17.0.1 x86_64

### Issue Description

When clicking 'Create New World' in a Singleplayer Menu, the game crashes shortly after.

I'm assuming this is a mod interaction, but I have no idea what would be causing it.

### Additional Information

[crash-2024-01-06_07.59.38-client.txt](https://github.com/Mrbysco/MimicWorld/files/13850274/crash-2024-01-06_07.59.38-client.txt)
Mod list is included at the bottom of the crash report.

**Comment by Mrbysco** [comment]
Can you provide the latest log?

**Comment by CraftyZombie** [comment]
Sure, here it is.
[latest.log](https://github.com/Mrbysco/MimicWorld/files/13850604/latest.log)

**Comment by Mrbysco** [comment]
Have you tried downgrading Forge? To something like 47.1.3? As that's the version I built against

**Comment by CraftyZombie** [comment]
Trying both latest Forge (47.2.19) and 47.1.3 seems to cause an instant crash when clicking the Singleplayer button.

I'm now doing this with only MimicWorld installed.
[crash-2024-01-06_10.34.36-client.txt](https://github.com/Mrbysco/MimicWorld/files/13850831/crash-2024-01-06_10.34.36-client.txt) (47.2.19)
[crash-2024-01-06_10.35.37-client.txt](https://github.com/Mrbysco/MimicWorld/files/13850832/crash-2024-01-06_10.35.37-client.txt) (47.1.3)


[latest.log](https://github.com/Mrbysco/MimicWorld/files/13850833/latest.log) (47.1.3)

**Comment by Mrbysco** [comment]
A fix is being built and uploaded

**Comment by CraftyZombie** [comment]
Thank you!
